---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:6.0.2
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    ports:
      - "127.0.0.1:8080:8081"
    expose:
      - "8080"
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADMIN_ENABLESERVER: "false"
      KAFKA_ADMIN_SERVER_PORT: 8081
      KAFKA_ADMIN_SERVERPORT: 8082
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    extra_hosts:
      - "moby:127.0.0.1"

